### ISSUE TITLE
tiktok downloader bug

### ISSUE THREAD

**Issue by e0o** [majhcc/social-media-downloader#5]
give me this video
https://ttdownloader.com/62d0670f6ca09e00aefc096e.mp4

**Comment by m7medVision** [comment]
نعم اني ما فهمت مو باغي؟

**Comment by e0o** [comment]
التيك توك يوم استعمل الميزة يعطيني هذا الفيديو مايعطيني الفيديو الى جبت رابطه فهمت؟

**Comment by e0o** [comment]
/: مافي حل؟

**Comment by m7medVision** [comment]
عب انا شغال سيده 


https://social-dl.majhcc.com this site uses same api

https://api-v1.majhcc.com/api/tk?url=https://www.tiktok.com/@majhc/video/7049993308386495745?is_from_webapp=v1&item_id=7049993308386495745

it works, furthermore M-API (api-v1.majhcc.com) will be closed next month.

**Comment by e0o** [comment]
تمام عشت
