### ISSUE TITLE
مافي حل؟

### ISSUE THREAD

**Issue by e0o** [majhcc/social-media-downloader#6]
![image](https://user-images.githubusercontent.com/62356945/187217380-154a32ae-69da-4089-87d3-444d3388e221.png)

**Comment by m7medVision** [comment]
هذا البوت ما حلي

**Comment by e0o** [comment]
عشت حليت المشكله

**Comment by e0o** [comment]
بس تويتر مو شغال ولا سناب

**Comment by m7medVision** [comment]
رسل اشوف

**Comment by e0o** [comment]
![image](https://user-images.githubusercontent.com/62356945/187247678-0594447a-da23-44d1-b674-2a44ab630607.png)

**Comment by m7medVision** [comment]
هيه شي حل شوف
 api-v1.majhcc.com/docs

**Comment by m7medVision** [comment]
و ترى السيرفر بيوقف بعد كم شهر ما معي فلوس الاجار هههههههههههههههههه 😂😂

**Comment by e0o** [comment]
دافع عليه كم؟

**Comment by m7medVision** [comment]
> دافع عليه كم؟

ما دافع شي بس شركة السيرفرات وقفت الخدمة المجانية

**Comment by e0o** [comment]
باخل على ريالين ماتشتري خادم من ديجتل اوشن

**Comment by m7medVision** [comment]
> باخل على ريالين ماتشتري خادم من ديجتل اوشن

انا ما معي فلوس رصيد هههههههههههههههههه 😂😂😂 خلاني اوفر

**Comment by e0o** [comment]
> > باخل على ريالين ماتشتري خادم من ديجتل اوشن
> 
> انت ما معي فلوس رصيد هههههههههههههههههه 😂😂😂 خلاني اوفر 

خلاص فتح لي ريبو حقهم انا برفعهم عندي

**Comment by m7medVision** [comment]
> > > باخل على ريالين ماتشتري خادم من ديجتل اوشن
> > 
> > انت ما معي فلوس رصيد هههههههههههههههههه 😂😂😂 خلاني اوفر 
> 
> خلاص فتح لي ريبو حقهم انا برفعهم عندي

اشترى سيرفر على قدك و ارفع عليه الapi و شغله و لاتنشره احسن لك
انا ترى شاري سيرفر بس رخيص ما يتحمل نص مليون ركوست في اليوم
